import React from 'react';

interface PixPaymentProps {
  amount: number;
  onConfirm: () => void;
  isLoading?: boolean;
}

export const PixPayment: React.FC<PixPaymentProps> = ({ amount, onConfirm, isLoading = false }) => {
  // In a real app, this would be generated by the backend
  const pixKey = '12345678901';
  
  const handleCopyPixKey = () => {
    navigator.clipboard.writeText(pixKey);
    alert('Chave PIX copiada para a área de transferência!');
  };
  
  return (
    <div className="text-center p-8 border border-dashed border-gray-300 rounded-md">
      <div className="mb-4">
        <svg className="w-16 h-16 mx-auto text-secondary" viewBox="0 0 24 24" fill="currentColor">
          <path d="M11.9999 2C6.47774 2 2 6.47774 2 12.0001C2 17.5223 6.47774 22 11.9999 22C17.5222 22 22 17.5223 22 12.0001C22 6.47774 17.5222 2 11.9999 2ZM16.5 8C17.3284 8 18 7.32843 18 6.5C18 5.67157 17.3284 5 16.5 5C15.6716 5 15 5.67157 15 6.5C15 7.32843 15.6716 8 16.5 8ZM7.5 8C8.32843 8 9 7.32843 9 6.5C9 5.67157 8.32843 5 7.5 5C6.67157 5 6 5.67157 6 6.5C6 7.32843 6.67157 8 7.5 8ZM11.9999 18.5C15.5899 18.5 18.5 15.5899 18.5 12C18.5 8.41015 15.5899 5.5 11.9999 5.5C8.41002 5.5 5.5 8.41015 5.5 12C5.5 15.5899 8.41002 18.5 11.9999 18.5Z"></path>
        </svg>
      </div>
      <h4 className="text-lg font-medium text-gray-800 mb-2">Pagamento via PIX</h4>
      <p className="text-gray-600 mb-4">
        Escaneie o código QR abaixo ou copie a chave PIX para realizar o pagamento de{' '}
        <span className="font-bold">
          {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(amount)}
        </span>
      </p>
      <div className="bg-white p-4 inline-block mb-4">
        <div className="w-48 h-48 bg-gray-200 mx-auto flex items-center justify-center">
          <span className="text-gray-500">Código QR PIX</span>
        </div>
      </div>
      <div className="mb-6">
        <p className="text-sm text-gray-500 mb-1">Chave PIX:</p>
        <div className="flex items-center justify-center">
          <span className="bg-gray-100 px-3 py-2 rounded text-gray-800">{pixKey}</span>
          <button
            type="button"
            className="ml-2 text-secondary hover:text-primary"
            onClick={handleCopyPixKey}
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"></path>
            </svg>
          </button>
        </div>
      </div>
      <p className="text-sm text-gray-500 mb-6">
        Após realizar o pagamento, clique em "Confirmar Pagamento" para concluir seu cadastro.
      </p>
      <button
        type="button"
        onClick={onConfirm}
        disabled={isLoading}
        className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-primary hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary"
      >
        {isLoading ? 'Processando...' : 'Confirmar Pagamento'}
      </button>
    </div>
  );
};
